name: build
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: Bump and Tag
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare Node 10
      uses: actions/setup-node@v2
      with:
        node-version: 10
    - run: npm install

    - name: Run Trivy vulnerability scanner fs dependency into package-lock.json
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: 'package-lock.json'
        ignore-unfixed: true
        # format: 'table'
        output: 'report-dependencies.json'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Generate tarball from image
      run: |
        docker build -t ci:1.0.0 .
        docker save -o vuln-image.tar ci:1.0.0
    
    - name: Run Trivy vulnerability scanner build image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ci:1.0.0'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        args: --format json --output-file result.json
        output: report-image.json
        severity: 'CRITICAL,HIGH'

    - name: upload result vul dependencies
      uses: actions/upload-artifact@v2
      with:
        name: report-vul-dependencies
        path: report-dependencies.json

    - name: upload result vul image base
      uses: actions/upload-artifact@v2
      with:
        name: report-vul-image
        path: report-image.json
