name: build
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  build:
    name: POC Runner Personal
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate tarball from image
      run: |
        docker build -t ci:1.0.0 .
        
    # - name: Run Trivy vulnerability scanner in tarball mode
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     input: /github/workspace/vuln-image.tar
    #     severity: 'CRITICAL,HIGH'
