name: build
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  bump-and-tag:
    env:
      GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    name: Bump and Tag
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get Tags
      run: git fetch origin +refs/tags/*:refs/tags/*

    - name: Bump Version
      id: bump_and_tag
      uses: konsentus/action.bump-version-and-tag@v1

    # - name: Bump version and push tag
    #   id: tag_version
    #   uses: miguelfito/github-bump-and-tag-action@v1
    #   with:
    #     github_token: ${{ secrets.GIT_TOKEN }}

    # - name: Create a GitHub release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    #   with:
    #     tag_name: ${{ steps.tag_version.outputs.new_tag }}
    #     release_name: Release ${{ steps.tag_version.outputs.new_tag }}
    #     body: ${{ steps.tag_version.outputs.changelog }}

    # - name: Bump version
    #   uses: remorses/bump-version@js
    #   with:
    #       version_file: ./VERSION
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Generate tarball from image
      run: |
        docker build -t ci:1.0.0 .
        docker save -o vuln-image.tar ci:1.0.0
        
    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        args: --format json --output-file result.json
        output: result.json
        severity: 'CRITICAL,HIGH'

    - name: upload result
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: result.json
