name: build
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    name: POC Runner Personal
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Bump version
    #   uses: remorses/bump-version@js
    #   with:
    #       version_file: ./VERSION
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Bump version
      uses: tkav/bump-version@explicit-option
      with:
          version_file: ./VERSION
          github_token: ${{ secrets.GIT_TOKEN }}
          explicit: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

    - name: Generate tarball from image
      run: |
        docker build -t ci:1.0.0 .
        docker save -o vuln-image.tar ci:1.0.0
        
    - name: Run Trivy vulnerability scanner in tarball mode
      uses: aquasecurity/trivy-action@master
      with:
        input: /github/workspace/vuln-image.tar
        args: --format json --output-file result.json
        output: result.json
        severity: 'CRITICAL,HIGH'

    - name: upload result
      uses: actions/upload-artifact@v2
      with:
        name: result
        path: result.json
