name: CI/CD Trivy Flow

on:
  push:
    branches:
      - master

permissions:
  contents: read
  security-events: write
  pull-requests: read

jobs:
  Trivy-FS:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 10.24.1
        - name: Install dependencies
          run: npm install
        - name: Run Trivy vulnerability scanner fs dependency into package-lock.json
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            scan-ref: '.'
            ignore-unfixed: true
            format: template
            template: '@/contrib/html.tpl'
            output: 'report-vuln-repositories.html'
            # format: 'table'
            # output: 'report-dependencies.json'
            severity: 'CRITICAL,HIGH,MEDIUM'

        - name: upload result vuln into package-lock.json to zip
          uses: actions/upload-artifact@v2
          with:
            name: report-vuln-repositories
            path: 'report-vuln-repositories.html'    

        - name: Run Trivy vulnerability scanner in repo mode
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            # scan-ref: 'package-lock.json'
            ignore-unfixed: true
            format: 'sarif'
            output: 'trivy-results.sarif'
            # template: '@/contrib/sarif.tpl'
            # output: 'trivy-results.sarif'
            # format: template
            # template: '@/contrib/html.tpl'
            # output: 'report-dependencies.html'
            # format: 'table'
            # output: 'report-dependencies.json'
            severity: 'CRITICAL,HIGH,MEDIUM'

        - name: Upload Trivy scan results to GitHub Security tab 
          uses: github/codeql-action/upload-sarif@v2
          with:
            sarif_file: 'trivy-results.sarif'

#   trivy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#         - uses: aquasecurity/trivy-action@master
#           name: Run Trivy vulnerability scanner fs dependency into package-lock.json
#           with:
#             scan-type: 'fs'
#             scan-ref: 'package-lock.json'
#             ignore-unfixed: true
#             format: template
#             template: '@/contrib/html.tpl'
#             output: 'report-dependencies.html'
#             # format: 'table'
#             # output: 'report-dependencies.json'
#             severity: 'CRITICAL,HIGH,MEDIUM'
